"""
Seed the coding_questions table with 375 DSA questions from
"DSA by Shradha Ma'am" spreadsheet.

Runs automatically on init_db() if the table is empty.
Idempotent — safe to call multiple times.
"""

# Each tuple: (topic, title, companies, remarks, difficulty)
# Difficulty is auto-assigned:
#   - Easy:   basic data-structure operations, simple traversals
#   - Medium: standard interview questions
#   - Hard:   advanced algorithms, DP, complex graph problems

QUESTIONS = [
    # ── Arrays ──
    ("Arrays", "Maximum and Minimum Element in an Array", "ABCO Accolite Amazon Cisco Hike Microsoft Snapdeal VMWare Google Adobe", "", "Easy"),
    ("Arrays", "Reverse the Array", "Infosys Moonfrog Labs", "", "Easy"),
    ("Arrays", "Maximum Subarray (Kadane's Algorithm)", "Microsoft Facebook", "use Kadane's Algorithm", "Medium"),
    ("Arrays", "Contains Duplicate", "Amazon", "", "Easy"),
    ("Arrays", "Chocolate Distribution Problem", "Amazon", "", "Easy"),
    ("Arrays", "Search in Rotated Sorted Array", "Microsoft Google Adobe Amazon D-E-Shaw Flipkart Hike Intuit MakeMyTrip Paytm", "", "Medium"),
    ("Arrays", "Next Permutation", "Uber Goldman Sachs Adobe", "", "Medium"),
    ("Arrays", "Best Time to Buy and Sell Stock", "Amazon D-E-Shaw Directi Flipkart Goldman Sachs Intuit MakeMyTrip Microsoft Ola Cabs Oracle Paytm Google", "", "Easy"),
    ("Arrays", "Repeat and Missing Number Array", "Amazon", "", "Medium"),
    ("Arrays", "Kth-Largest Element in an Array", "Amazon Microsoft Walmart Adobe", "", "Medium"),
    ("Arrays", "Trapping Rain Water", "Samsung", "use auxiliary arrays", "Hard"),
    ("Arrays", "Product of Array Except Self", "Microsoft Facebook", "", "Medium"),
    ("Arrays", "Maximum Product Subarray", "Amazon D-E-Shaw Microsoft Morgan Stanley OYO Rooms Google", "", "Medium"),
    ("Arrays", "Find Minimum in Rotated Sorted Array", "Adobe Amazon Microsoft Morgan Stanley Samsung Snapdeal Times Internet", "", "Medium"),
    ("Arrays", "Find Pair with Sum in Sorted & Rotated Array", "Microsoft Google Apple", "", "Medium"),
    ("Arrays", "3Sum", "Adobe Amazon Microsoft Morgan Stanley Samsung Snapdeal Times Internet", "", "Medium"),
    ("Arrays", "Container With Most Water", "Flipkart Dunzo", "use 2 pointer approach", "Medium"),
    ("Arrays", "Given Sum Pair", "Infosys Amazon Flipkart", "", "Easy"),
    ("Arrays", "Kth Smallest Element", "ABCO Accolite Amazon Cisco Hike Microsoft Snapdeal VMWare Google Adobe", "", "Medium"),
    ("Arrays", "Merge Overlapping Intervals", "Google", "", "Medium"),
    ("Arrays", "Find Minimum Number of Merge Operations to Make an Array Palindrome", "Amazon", "", "Hard"),
    ("Arrays", "Arrange Numbers to Form the Biggest Number", "Barclays", "", "Medium"),
    ("Arrays", "Space Optimization Using Bit Manipulations", "Amazon", "", "Hard"),
    ("Arrays", "Subarray Sum Divisible K", "Snapdeal Microsoft", "", "Medium"),
    ("Arrays", "Print all Possible Combinations of r Elements in a Given Array of Size n", "Amazon", "", "Medium"),
    ("Arrays", "Mo's Algorithm", "Microsoft", "", "Hard"),

    # ── Strings ──
    ("Strings", "Valid Palindrome", "Amazon Cisco D-E-Shaw Facebook FactSet Morgan Stanley Paytm Zoho", "", "Easy"),
    ("Strings", "Valid Anagram", "Nagarro Media.net Directi Google Adobe Flipkart", "", "Easy"),
    ("Strings", "Valid Parentheses", "Google", "use Stacks (if possible)", "Easy"),
    ("Strings", "Remove Consecutive Characters", "Samsung Adobe", "", "Easy"),
    ("Strings", "Longest Common Prefix", "Adobe Grofers Dunzo", "", "Easy"),
    ("Strings", "Convert Sentence to Mobile Numeric Keypad Sequence", "Adobe", "", "Medium"),
    ("Strings", "Print all the Duplicates in the Input String", "Ola Amdocs", "", "Easy"),
    ("Strings", "Longest Substring without Repeating Characters", "Morgan Stanley Amazon", "", "Medium"),
    ("Strings", "Longest Repeating Character Replacement", "Amazon Google", "", "Medium"),
    ("Strings", "Group Anagrams", "Samsung Adobe Amazon", "", "Medium"),
    ("Strings", "Longest Palindromic Substring", "Microsoft Google Samsung Visa", "", "Medium"),
    ("Strings", "Palindromic Substrings", "Microsoft", "", "Medium"),
    ("Strings", "Next Permutation (String)", "Adobe Goldman Sachs Uber", "", "Medium"),
    ("Strings", "Count Palindromic Subsequences", "Myntra", "", "Hard"),
    ("Strings", "Smallest Window Containing All Characters of Another String", "Microsoft Amazon", "", "Hard"),
    ("Strings", "Wildcard String Matching", "Microsoft Amazon Ola", "", "Hard"),
    ("Strings", "Longest Prefix Suffix", "Flipkart Swiggy", "", "Medium"),
    ("Strings", "Rabin-Karp Algorithm for Pattern Searching", "Microsoft", "", "Hard"),
    ("Strings", "Transform One String to Another using Minimum Operations", "Directi", "", "Hard"),
    ("Strings", "Minimum Window Substring", "Amazon Google MakeMyTrip Microsoft Media.net Atlassian Flipkart", "", "Hard"),
    ("Strings", "Boyer Moore Algorithm for Pattern Searching", "Amdocs", "", "Hard"),
    ("Strings", "Word Wrap", "Microsoft", "use Dynamic Programming", "Hard"),

    # ── 2D Arrays ──
    ("2D Arrays", "Zigzag (Diagonal) Traversal of Matrix", "Amazon", "", "Medium"),
    ("2D Arrays", "Set Matrix Zeroes", "Amazon Microsoft", "", "Medium"),
    ("2D Arrays", "Spiral Matrix", "Flipkart Apple Societe Generale", "", "Medium"),
    ("2D Arrays", "Rotate Image", "Microsoft Paytm Samsung Adobe", "", "Medium"),
    ("2D Arrays", "Word Search", "Google Ola Goldman Sachs", "", "Medium"),
    ("2D Arrays", "Find the Number of Islands (Using DFS)", "Microsoft Uber Apple Amazon", "Read about DFS", "Medium"),
    ("2D Arrays", "Replace O with X if Surrounded by X", "Google", "", "Medium"),
    ("2D Arrays", "Find Common Element in All Rows of Sorted Matrix", "MAQ Software Microsoft VMWare", "", "Medium"),
    ("2D Arrays", "Create Matrix with Alternating Rectangles of O and X", "MAQ VMWare", "", "Easy"),
    ("2D Arrays", "Maximum Size Rectangle of All 1s", "Amazon Microsoft", "", "Hard"),

    # ── Searching & Sorting ──
    ("Searching & Sorting", "Permute Two Arrays such that Sum >= K", "Samsung", "", "Easy"),
    ("Searching & Sorting", "Counting Sort", "Samsung Morgan Stanley Snapdeal EPAM Systems", "", "Easy"),
    ("Searching & Sorting", "Find Common Elements in Three Sorted Arrays", "MAQ Software Microsoft VMWare", "", "Easy"),
    ("Searching & Sorting", "Searching in Array where Adjacent Differ by at Most K", "TCS Amazon", "", "Medium"),
    ("Searching & Sorting", "Ceiling in a Sorted Array", "TCS", "", "Easy"),
    ("Searching & Sorting", "Pair with Given Difference", "Amazon Visa", "", "Easy"),
    ("Searching & Sorting", "Majority Element", "Amazon Google", "", "Easy"),
    ("Searching & Sorting", "Count Triplets with Sum Smaller than Given Value", "Amazon SAP Labs", "", "Medium"),
    ("Searching & Sorting", "Maximum Sum Subsequence with No Adjacent Elements", "Amazon FactSet OYO Rooms Paytm Walmart Yahoo Adobe Flipkart", "", "Medium"),
    ("Searching & Sorting", "Merge Sorted Arrays using O(1) Space", "Amdocs Goldman Sachs Juniper LinkedIn Microsoft Snapdeal Adobe", "", "Hard"),
    ("Searching & Sorting", "Inversion of Array", "Adobe Amazon BankBazaar Flipkart Microsoft Myntra MakeMyTrip", "", "Hard"),
    ("Searching & Sorting", "Find Duplicates in O(n) Time and O(1) Space", "Amazon D-E-Shaw Flipkart Paytm Qualcomm Zoho", "", "Medium"),
    ("Searching & Sorting", "Radix Sort", "Amazon Microsoft", "", "Medium"),
    ("Searching & Sorting", "Product of Array Except Itself", "Accolite Amazon D-E-Shaw Intuit Morgan Stanley Microsoft Flipkart", "", "Medium"),
    ("Searching & Sorting", "Make All Array Elements Equal", "Amazon", "", "Medium"),
    ("Searching & Sorting", "Check if Reversing a Sub Array Makes the Array Sorted", "Amazon", "", "Medium"),
    ("Searching & Sorting", "Find Four Elements that Sum to a Given Value", "Adobe Amazon Google Microsoft OYO Rooms", "", "Hard"),
    ("Searching & Sorting", "Median of Two Sorted Arrays with Different Size", "Amazon Samsung Microsoft Google", "", "Hard"),
    ("Searching & Sorting", "Median of Stream of Running Integers", "Amazon Google", "", "Hard"),
    ("Searching & Sorting", "Print Subarrays with 0 Sum", "Paytm Adobe", "", "Medium"),
    ("Searching & Sorting", "Aggressive Cows", "Adobe", "", "Hard"),
    ("Searching & Sorting", "Allocate Minimum Number of Pages", "Google Infosys Codenation Amazon Microsoft", "", "Hard"),
    ("Searching & Sorting", "Minimum Swaps to Sort", "Amazon Google", "", "Medium"),

    # ── Backtracking ──
    ("Backtracking", "Rat in a Maze", "Microsoft Amazon", "", "Medium"),
    ("Backtracking", "Combination Sum", "Adobe Amazon Microsoft", "", "Medium"),
    ("Backtracking", "Crossword Puzzle", "Microsoft", "", "Hard"),
    ("Backtracking", "Longest Possible Route in a Matrix with Hurdles", "Microsoft", "", "Hard"),
    ("Backtracking", "N-Queen Problem (All Solutions)", "Accolite Amazon Amdocs D-E-Shaw MAQ Software Twitter Visa Microsoft", "", "Hard"),
    ("Backtracking", "Solve the Sudoku", "Amazon Directi Flipkart MakeMyTrip MAQ Software Microsoft Ola Oracle PayPal Zoho", "", "Hard"),
    ("Backtracking", "Partition Equal Subset Sum", "Amazon Adobe Accolite Traveloka", "", "Medium"),
    ("Backtracking", "M Coloring Problem", "Amazon", "", "Hard"),
    ("Backtracking", "Knight's Tour", "IBM", "", "Hard"),
    ("Backtracking", "Remove Invalid Parentheses", "Uber", "", "Hard"),
    ("Backtracking", "Word Break Problem using Backtracking", "", "", "Hard"),
    ("Backtracking", "Print all Palindromic Partitions of a String", "Facebook Amazon Microsoft", "", "Hard"),
    ("Backtracking", "Find Shortest Safe Route in a Path with Landmines", "Facebook Amazon Microsoft", "", "Hard"),
    ("Backtracking", "Partition of Set into K Subsets with Equal Sum", "Amazon", "", "Hard"),
    ("Backtracking", "Hamiltonian Cycle", "Amazon", "", "Hard"),
    ("Backtracking", "Tug of War", "Google", "", "Hard"),
    ("Backtracking", "Maximum Possible Number by Doing at Most K Swaps", "Amazon Adobe Accolite Traveloka", "", "Hard"),
    ("Backtracking", "Solving Cryptarithmetic Puzzles", "Goldman Sachs", "", "Hard"),
    ("Backtracking", "Find Paths from Corner Cell to Middle Cell in Maze", "Meta", "", "Medium"),
    ("Backtracking", "Arithmetic Expressions", "Flipkart", "", "Hard"),

    # ── Linked List ──
    ("Linked List", "Reverse Linked List", "Sprinklr", "", "Easy"),
    ("Linked List", "Linked List Cycle Detection", "Accolite Amazon D-E-Shaw Hike MakeMyTrip MAQ Software OYO Rooms Paytm Samsung SAP Labs Snapdeal VMWare Walmart Adobe", "", "Easy"),
    ("Linked List", "Merge Two Sorted Lists", "Accolite Amazon Brocade FactSet Flipkart MakeMyTrip Microsoft Oracle Samsung Zoho", "", "Easy"),
    ("Linked List", "Delete without Head Node", "Amazon Goldman Sachs Microsoft Samsung Visa", "", "Easy"),
    ("Linked List", "Remove Duplicates from Unsorted Linked List", "Amazon Intuit", "", "Easy"),
    ("Linked List", "Sort Linked List of 0s, 1s, or 2s", "Microsoft Amazon MakeMyTrip", "", "Medium"),
    ("Linked List", "Multiply Two Numbers Represented as Linked Lists", "Amazon", "", "Medium"),
    ("Linked List", "Remove Nth Node from End of List", "Accolite Adobe Amazon FactSet MAQ Software Morgan Stanley OYO Rooms Qualcomm Samsung Snapdeal Flipkart", "", "Medium"),
    ("Linked List", "Reorder List", "Amazon Microsoft OYO Rooms Intuit", "", "Medium"),
    ("Linked List", "Detect and Remove Loop in a Linked List", "Accolite Amazon D-E-Shaw Hike MakeMyTrip MAQ Software OYO Rooms Paytm Samsung SAP Labs Snapdeal VMWare Walmart Adobe", "", "Medium"),
    ("Linked List", "Intersection Point of Two Linked Lists", "Amazon", "", "Medium"),
    ("Linked List", "Flatten a Linked List with Next and Child Pointers", "Google", "", "Hard"),
    ("Linked List", "Linked List in Zig-Zag Fashion", "Microsoft", "", "Medium"),
    ("Linked List", "Reverse a Doubly Linked List", "Walmart", "", "Easy"),
    ("Linked List", "Delete Nodes with Greater Value on Right Side", "Amazon", "", "Medium"),
    ("Linked List", "Segregate Even and Odd Elements in a Linked List", "Walmart", "", "Medium"),
    ("Linked List", "Point to Next Higher Value Node with Arbitrary Pointer", "GeekyAnts", "", "Hard"),
    ("Linked List", "Rearrange a Given Linked List in Place", "Ola Uber", "", "Medium"),
    ("Linked List", "Sort Biotonic Doubly Linked Lists", "Morgan Stanley", "", "Hard"),
    ("Linked List", "Merge K Sorted Lists", "Microsoft Ola eBay", "", "Hard"),
    ("Linked List", "Merge Sort for Linked List", "Accolite Adobe Amazon MAQ Software Microsoft Paytm Veritas", "Important", "Hard"),
    ("Linked List", "Quicksort on Singly-Linked List", "Paytm", "Important", "Hard"),
    ("Linked List", "Sum of Two Linked Lists", "Accolite Amazon Flipkart MakeMyTrip Microsoft Morgan Stanley Qualcomm Snapdeal", "", "Medium"),
    ("Linked List", "Flattening a Linked List", "24x7 Innovation Labs Amazon Drishti-Soft Flipkart Goldman Sachs Microsoft Paytm Qualcomm Snapdeal Visa", "", "Hard"),
    ("Linked List", "Clone a Linked List with Next and Random Pointer", "Triology", "", "Hard"),
    ("Linked List", "Subtract Two Numbers Represented as Linked Lists", "Amazon Goldman Sachs", "", "Medium"),

    # ── Stacks & Queues ──
    ("Stacks & Queues", "Implement Two Stacks in an Array", "24x7 Innovation Labs Microsoft Samsung Snapdeal", "", "Easy"),
    ("Stacks & Queues", "Evaluation of Postfix Expression", "Amazon Google Facebook", "", "Medium"),
    ("Stacks & Queues", "Implement Stack using Queues", "Facebook", "", "Easy"),
    ("Stacks & Queues", "Queue Reversal", "Amazon Morgan Stanley", "", "Easy"),
    ("Stacks & Queues", "Implement Stack/Queue using Deque", "Microsoft Atlassian", "", "Easy"),
    ("Stacks & Queues", "Reverse First K Elements of Queue", "Microsoft Amdocs", "", "Easy"),
    ("Stacks & Queues", "Design Stack with Middle Operation", "MAQ Software", "", "Medium"),
    ("Stacks & Queues", "Infix to Postfix", "Amazon Samsung Paytm VMWare", "", "Medium"),
    ("Stacks & Queues", "Design and Implement Special Stack", "Amazon Google Microsoft Visa Goldman Sachs", "", "Medium"),
    ("Stacks & Queues", "Longest Valid String", "Google Microsoft", "", "Hard"),
    ("Stacks & Queues", "Find if Expression has Duplicate Parenthesis", "Flipkart Oracle OYO Rooms Snapdeal Walmart Microsoft Google", "", "Medium"),
    ("Stacks & Queues", "Stack Permutations", "Visa", "", "Medium"),
    ("Stacks & Queues", "Count Natural Numbers whose Permutation > Number", "Amazon", "", "Hard"),
    ("Stacks & Queues", "Sort a Stack using Recursion", "Amazon Goldman Sachs IBM Intuit Yahoo Microsoft", "", "Medium"),
    ("Stacks & Queues", "First Non-Repeating Character in a Stream", "Microsoft Flipkart", "", "Medium"),
    ("Stacks & Queues", "The Celebrity Problem", "Google Visa Apple", "", "Medium"),
    ("Stacks & Queues", "Next Larger Element", "Visa", "", "Medium"),
    ("Stacks & Queues", "Distance of Nearest Cell Having 1", "Flipkart Facebook", "", "Medium"),
    ("Stacks & Queues", "Rotten Oranges", "Facebook", "", "Medium"),
    ("Stacks & Queues", "Next Smaller Element", "Codenation", "", "Medium"),
    ("Stacks & Queues", "Circular Tour", "Codenation Flipkart", "", "Medium"),
    ("Stacks & Queues", "Efficiently Implement K Stacks in Single Array", "Flipkart", "", "Hard"),
    ("Stacks & Queues", "Iterative Tower of Hanoi", "Microsoft Flipkart", "", "Hard"),
    ("Stacks & Queues", "Maximum of Minimums for Every Window Size", "Amazon Microsoft Flipkart", "", "Hard"),
    ("Stacks & Queues", "LRU Cache Implementation", "Microsoft Uber Alibaba", "", "Hard"),
    ("Stacks & Queues", "Find a Tour that Visits All Stations", "Uber", "", "Medium"),

    # ── Greedy ──
    ("Greedy", "Activity Selection Problem", "Facebook Morgan Stanley Flipkart", "", "Easy"),
    ("Greedy", "Minimum Number of Coins", "Accolite Amazon Morgan Stanley Oracle Paytm Samsung Snapdeal Visa Microsoft Google", "", "Easy"),
    ("Greedy", "Minimum Sum of Two Numbers Formed from Digits of Array", "Google", "", "Medium"),
    ("Greedy", "Minimum Sum of Absolute Difference of Pairs", "Amazon", "", "Easy"),
    ("Greedy", "Maximum Height Pyramid from Given Array", "Flipkart Amazon", "", "Medium"),
    ("Greedy", "Minimum Cost for Acquiring All Coins with K Extra Allowed", "", "", "Medium"),
    ("Greedy", "Find Maximum Equal Sum of Every Three Stacks", "Microsoft Amazon Flipkart", "", "Medium"),
    ("Greedy", "Job Sequencing Problem", "Microsoft Accolite", "", "Medium"),
    ("Greedy", "Egyptian Fraction", "", "", "Medium"),
    ("Greedy", "Fractional Knapsack Problem", "Microsoft", "", "Medium"),
    ("Greedy", "Maximum Length Chain of Pairs", "Amazon Microsoft", "", "Medium"),
    ("Greedy", "Find Smallest Number with Given Digits and Sum", "MAQ Software OYO Rooms", "", "Medium"),
    ("Greedy", "Maximize Sum of Consecutive Differences in Circular Array", "Maccafe", "", "Medium"),
    ("Greedy", "Paper Cut: Minimum Number of Squares", "Google", "", "Hard"),
    ("Greedy", "Lexicographically Smallest Array with K Consecutive Swaps", "Amazon", "", "Hard"),
    ("Greedy", "CHOCOLA Problem", "Flipkart", "", "Hard"),
    ("Greedy", "Find Minimum Time to Finish All Jobs", "", "", "Hard"),
    ("Greedy", "Job Sequencing using Disjoint Set Union", "Samsung", "", "Hard"),
    ("Greedy", "Rearrange Characters so No Two Adjacent Are Same", "Amazon Microsoft", "", "Medium"),
    ("Greedy", "Minimum Edges to Reverse for Path from Source to Destination", "", "", "Hard"),
    ("Greedy", "Minimize Cash Flow Among Friends", "", "", "Hard"),
    ("Greedy", "Minimum Cost to Cut a Board into Squares", "Maccafe", "", "Hard"),

    # ── Binary Trees ──
    ("Binary Trees", "Maximum Depth of Binary Tree", "Amazon Cadence India D-E-Shaw FactSet MakeMyTrip", "", "Easy"),
    ("Binary Trees", "Reverse Level Order Traversal", "Amazon Microsoft Flipkart Adobe", "", "Easy"),
    ("Binary Trees", "Subtree of Another Tree", "Amazon Microsoft Facebook", "", "Easy"),
    ("Binary Trees", "Invert Binary Tree", "Amazon Hike", "", "Easy"),
    ("Binary Trees", "Binary Tree Level Order Traversal", "Accolite Adobe Amazon Cisco D-E-Shaw Flipkart", "", "Easy"),
    ("Binary Trees", "Left View of Binary Tree", "Microsoft Adobe Cisco", "", "Easy"),
    ("Binary Trees", "Right View of Binary Tree", "Amdocs", "", "Easy"),
    ("Binary Trees", "ZigZag Tree Traversal", "Amazon Cisco FactSet Hike Snapdeal Walmart Microsoft Flipkart", "", "Medium"),
    ("Binary Trees", "Create a Mirror Tree", "Accolite Adobe Amazon Goldman Sachs Microsoft Morgan Stanley Myntra Ola Paytm", "", "Easy"),
    ("Binary Trees", "Check if All Leaves are at Same Level", "Amazon", "", "Easy"),
    ("Binary Trees", "Check for Balanced Tree", "Amazon Walmart Microsoft", "", "Easy"),
    ("Binary Trees", "Transform to Sum Tree", "Amazon FactSet Microsoft Samsung Walmart", "", "Medium"),
    ("Binary Trees", "Check if Tree is Isomorphic", "Amazon Microsoft", "", "Medium"),
    ("Binary Trees", "Same Tree", "Amazon Microsoft Flipkart", "", "Easy"),
    ("Binary Trees", "Construct Binary Tree from Preorder and Inorder", "Accolite Amazon Microsoft", "", "Medium"),
    ("Binary Trees", "Height of Binary Tree", "Amazon Cadence India D-E-Shaw FactSet MakeMyTrip", "", "Easy"),
    ("Binary Trees", "Diameter of a Binary Tree", "Amazon Microsoft OYO Rooms", "", "Medium"),
    ("Binary Trees", "Top View of Binary Tree", "Microsoft Adobe Expedia", "", "Medium"),
    ("Binary Trees", "Bottom View of Binary Tree", "DE Shaw India", "", "Medium"),
    ("Binary Trees", "Diagonal Traversal of Binary Tree", "Amazon Microsoft", "", "Medium"),
    ("Binary Trees", "Boundary Traversal of Binary Tree", "Accolite Amazon FactSet Hike", "", "Medium"),
    ("Binary Trees", "Construct Binary Tree from String with Brackets", "Microsoft Morgan Stanley OYO Rooms Samsung Snapdeal Flipkart", "", "Hard"),
    ("Binary Trees", "Minimum Swaps to Convert BT to BST", "Adobe Amazon", "", "Hard"),
    ("Binary Trees", "Duplicate Subtree in Binary Tree", "Google", "", "Medium"),
    ("Binary Trees", "Check if a Given Graph is Tree or Not", "Microsoft Amazon", "", "Medium"),
    ("Binary Trees", "Lowest Common Ancestor in a Binary Tree", "Accolite Amazon Cisco Expedia Flipkart MakeMyTrip Microsoft OYO", "", "Medium"),
    ("Binary Trees", "Min Distance Between Two Given Nodes", "Amazon LinkedIn MakeMyTrip Ola Qualcomm Samsung", "", "Medium"),
    ("Binary Trees", "Duplicate Subtrees", "Ola", "", "Medium"),
    ("Binary Trees", "Kth Ancestor of a Node in Binary Tree", "Josh Technology Group", "", "Hard"),
    ("Binary Trees", "Binary Tree Maximum Path Sum", "Samsung Facebook", "", "Hard"),
    ("Binary Trees", "Serialize and Deserialize Binary Tree", "Flipkart LinkedIn MAQ Software Microsoft Paytm Yahoo", "", "Hard"),
    ("Binary Trees", "Binary Tree to DLL", "Accolite Amazon Goldman Sachs Microsoft Morgan Stanley Salesforce Snapdeal", "", "Hard"),
    ("Binary Trees", "Print All K-Sum Paths in a Binary Tree", "Accolite Amazon Goldman Sachs", "", "Hard"),

    # ── Binary Search Trees ──
    ("Binary Search Trees", "Lowest Common Ancestor of a BST", "Accolite Amazon Flipkart MAQ Software Microsoft Samsung Synopsys", "", "Easy"),
    ("Binary Search Trees", "BST Search and Insertion", "Accolite Amazon Microsoft Paytm Samsung", "", "Easy"),
    ("Binary Search Trees", "Minimum Element in BST", "Microsoft", "", "Easy"),
    ("Binary Search Trees", "Predecessor and Successor", "Google Adobe Goldman Sachs Directi", "", "Medium"),
    ("Binary Search Trees", "Check Whether BST Contains Dead End", "Walmart", "", "Medium"),
    ("Binary Search Trees", "Binary Tree to BST", "HSBC", "", "Medium"),
    ("Binary Search Trees", "Kth Largest Element in BST", "Accolite Amazon Samsung SAP Labs Microsoft", "", "Medium"),
    ("Binary Search Trees", "Validate Binary Search Tree", "OYO Rooms Qualcomm Samsung Snapdeal VMWare Walmart Amazon Facebook", "", "Medium"),
    ("Binary Search Trees", "Kth Smallest Element in a BST", "Accolite Amazon Google", "", "Medium"),
    ("Binary Search Trees", "Delete Node in a BST", "Adobe Barclays", "", "Medium"),
    ("Binary Search Trees", "Flatten BST to Sorted List", "Microsoft", "", "Medium"),
    ("Binary Search Trees", "Preorder to Postorder", "Amazon LinkedIn Flipkart", "", "Medium"),
    ("Binary Search Trees", "Count BST Nodes in a Given Range", "D-E-Shaw Google", "", "Medium"),
    ("Binary Search Trees", "Populate Inorder Successor for All Nodes", "SAP Labs", "", "Medium"),
    ("Binary Search Trees", "Convert Normal BST to Balanced BST", "Paytm", "", "Medium"),
    ("Binary Search Trees", "Merge Two BSTs", "DE Shaw India", "", "Hard"),
    ("Binary Search Trees", "Find All Conflicting Appointments", "Samsung", "", "Hard"),
    ("Binary Search Trees", "Replace Every Element with Least Greater Element on Right", "Samsung", "", "Hard"),
    ("Binary Search Trees", "Construct BST from Given Preorder Traversal", "Adobe Morgan Stanley Microsoft", "", "Medium"),
    ("Binary Search Trees", "Find Median of BST in O(n) Time and O(1) Space", "Amazon", "", "Hard"),
    ("Binary Search Trees", "Largest BST in a Binary Tree", "Amazon D-E-Shaw Samsung Microsoft Flipkart", "Important", "Hard"),

    # ── Heaps & Hashing ──
    ("Heaps & Hashing", "Choose K Array Elements to Minimize Max-Min Difference", "", "", "Easy"),
    ("Heaps & Hashing", "Heap Sort", "Adobe", "", "Medium"),
    ("Heaps & Hashing", "Top K Frequent Elements", "Amazon Microsoft", "", "Medium"),
    ("Heaps & Hashing", "K Largest Elements in an Array", "Amazon Microsoft Walmart Adobe", "", "Medium"),
    ("Heaps & Hashing", "Next Greater Element", "Amazon Microsoft Flipkart Adobe", "", "Medium"),
    ("Heaps & Hashing", "Kth Smallest/Largest Element in Unsorted Array", "ABCO Accolite Amazon Cisco Hike Microsoft Snapdeal VMWare Google Adobe", "", "Medium"),
    ("Heaps & Hashing", "Find Maximum Repeating Number in O(n) Time O(1) Space", "Accolite Amazon", "", "Medium"),
    ("Heaps & Hashing", "Kth Smallest Element After Removing Some Integers", "ABCO Accolite Amazon Cisco Hike Microsoft Snapdeal VMWare Google Adobe", "", "Hard"),
    ("Heaps & Hashing", "Find K Closest Elements to a Given Value", "Amazon OYO Rooms", "", "Medium"),
    ("Heaps & Hashing", "Kth Largest Element in a Stream", "Amazon Cisco Hike OYO Rooms Walmart Microsoft Flipkart", "", "Medium"),
    ("Heaps & Hashing", "Connect Ropes (Minimum Cost)", "Amazon OYO Goldman Sachs", "", "Medium"),
    ("Heaps & Hashing", "Cuckoo Hashing", "Amazon", "", "Hard"),
    ("Heaps & Hashing", "Itinerary from a List of Tickets", "Microsoft Ola eBay", "", "Medium"),
    ("Heaps & Hashing", "Largest Subarray with 0 Sum", "Amazon MakeMyTrip Microsoft", "", "Medium"),
    ("Heaps & Hashing", "Count Distinct Elements in Every Window of Size K", "Accolite Amazon Microsoft", "", "Medium"),
    ("Heaps & Hashing", "Group Shifted Strings", "Oracle", "", "Medium"),
    ("Heaps & Hashing", "Merge K Sorted Lists", "Microsoft Ola eBay", "", "Hard"),
    ("Heaps & Hashing", "Find Median from Data Stream", "Adobe Amazon Apple Facebook Flipkart Google Microsoft Morgan Stanley Oracle Samsung Yahoo", "", "Hard"),
    ("Heaps & Hashing", "Sliding Window Maximum", "Amazon Directi Flipkart Microsoft Google", "", "Hard"),
    ("Heaps & Hashing", "Find the Smallest Positive Number Missing", "Accolite Amazon Samsung Snapdeal", "", "Medium"),
    ("Heaps & Hashing", "Find Surpasser Count of Each Element", "Amazon Morgan Stanley Ola SAP Labs", "", "Hard"),
    ("Heaps & Hashing", "Tournament Tree and Binary Heap", "Amazon Ola Samsung Synopsys Walmart Microsoft", "", "Hard"),
    ("Heaps & Hashing", "Check for Palindrome (Hashing)", "Amazon Cisco D-E-Shaw Facebook FactSet Morgan Stanley Paytm Zoho", "", "Easy"),
    ("Heaps & Hashing", "Length of Largest Subarray with Contiguous Elements", "Amazon Intuit Microsoft", "", "Medium"),
    ("Heaps & Hashing", "Palindrome Substring Queries", "Amazon Morgan Stanley Ola SAP Labs", "", "Hard"),
    ("Heaps & Hashing", "Subarray with Distinct Elements", "Microsoft Ola eBay", "", "Medium"),
    ("Heaps & Hashing", "Find the Recurring Function", "MAQ Software", "", "Medium"),
    ("Heaps & Hashing", "K Maximum Sum Combinations from Two Arrays", "Amazon", "", "Hard"),

    # ── Graphs ──
    ("Graphs", "BFS Traversal", "Samsung Delhivery SAP Labs", "", "Easy"),
    ("Graphs", "DFS Traversal", "Samsung Intuit Goldman Sachs", "", "Easy"),
    ("Graphs", "Flood Fill Algorithm", "Google Adobe Apple", "", "Easy"),
    ("Graphs", "Number of Triangles in Graph", "IBM", "", "Medium"),
    ("Graphs", "Detect Cycle in a Directed Graph", "Lenskart", "", "Medium"),
    ("Graphs", "Detect Cycle in an Undirected Graph", "Samsung", "", "Medium"),
    ("Graphs", "Rat in a Maze Problem (Graph)", "Sharechat Directi", "", "Medium"),
    ("Graphs", "Steps by Knight", "Samsung", "", "Medium"),
    ("Graphs", "Clone Graph", "Google MAQ Software Apple Facebook", "", "Medium"),
    ("Graphs", "Number of Operations to Make Network Connected", "Samsung", "", "Medium"),
    ("Graphs", "Dijkstra's Shortest Path Algorithm", "Amazon", "", "Medium"),
    ("Graphs", "Topological Sort", "Amazon Google Flipkart OYO Samsung", "", "Medium"),
    ("Graphs", "Oliver and the Game", "Sharechat Directi", "", "Hard"),
    ("Graphs", "Minimum Time for Each Job (DAG)", "Amazon", "", "Hard"),
    ("Graphs", "Check if All Tasks Can Be Finished (Dependencies)", "Directi Sharechat", "", "Medium"),
    ("Graphs", "Find the Number of Islands", "Razorpay", "", "Medium"),
    ("Graphs", "Prim's Minimum Spanning Tree", "Visa", "", "Medium"),
    ("Graphs", "Negative Weighted Cycle Detection", "Amazon", "", "Hard"),
    ("Graphs", "Floyd Warshall All-Pairs Shortest Path", "Google Uber", "", "Hard"),
    ("Graphs", "Graph Coloring", "Morgan Stanley", "", "Hard"),
    ("Graphs", "Snakes and Ladders", "Goldman Sachs MakeMyTrip", "", "Medium"),
    ("Graphs", "Kosaraju's Algorithm (Strongly Connected Components)", "Paytm", "", "Hard"),
    ("Graphs", "Journey to the Moon", "Lenskart", "", "Hard"),
    ("Graphs", "Vertex Cover Problem", "Intuit", "", "Hard"),
    ("Graphs", "M Coloring Problem (Graph)", "Uber", "", "Hard"),
    ("Graphs", "Cheapest Flights Within K Stops", "Uber PayPal", "", "Hard"),
    ("Graphs", "Path of More than K Length from a Source", "Cisco Intuit", "", "Hard"),
    ("Graphs", "Bellman-Ford Algorithm", "Sharechat Directi", "", "Hard"),
    ("Graphs", "Bipartite Graph Check", "Microsoft Flipkart", "", "Medium"),
    ("Graphs", "Word Ladder", "Microsoft", "", "Hard"),
    ("Graphs", "Alien Dictionary", "Samsung", "", "Hard"),
    ("Graphs", "Kruskal's MST", "Amazon Cisco Samsung", "Important", "Hard"),
    ("Graphs", "Total Number of Spanning Trees in a Graph", "Amazon Cisco Samsung Microsoft Flipkart", "", "Hard"),
    ("Graphs", "Travelling Salesman Problem", "Google Microsoft Opera", "Important", "Hard"),
    ("Graphs", "Longest Path in a DAG", "Google", "", "Hard"),
    ("Graphs", "Two Clique Problem", "Microsoft", "", "Hard"),
    ("Graphs", "Minimise the Cashflow", "Intuit Uber", "", "Hard"),
    ("Graphs", "Chinese Postman Problem", "Intuit", "", "Hard"),
    ("Graphs", "Water Jug Problem", "Intuit Uber", "", "Medium"),
    ("Graphs", "Water Jug Problem (BFS)", "MakeMyTrip MAQ Software", "", "Medium"),

    # ── Tries ──
    ("Tries", "Construct a Trie from Scratch", "Accolite Amazon D-E-Shaw FactSet Microsoft", "", "Medium"),
    ("Tries", "Print Unique Rows in a Given Boolean Matrix", "Amazon Zoho", "", "Medium"),
    ("Tries", "Word Break Problem (Trie Solution)", "Amazon Google Hike IBM MAQ Software Microsoft Walmart Zoho", "", "Hard"),
    ("Tries", "Print All Anagrams Together", "Amazon D-E-Shaw Goldman Sachs Morgan Stanley Snapdeal Microsoft", "", "Medium"),
    ("Tries", "Shortest Unique Prefix for Every Word", "Microsoft Google", "", "Hard"),
    ("Tries", "Implement a Phone Directory", "Amazon Microsoft Snapdeal", "", "Medium"),

    # ── Dynamic Programming ──
    ("DP", "Knapsack with Duplicate Items", "Amazon", "", "Medium"),
    ("DP", "BBT Counter", "Microsoft", "", "Medium"),
    ("DP", "Reach a Given Score", "Samsung", "", "Easy"),
    ("DP", "Maximum Difference of Zeros and Ones in Binary String", "Ola", "", "Medium"),
    ("DP", "Climbing Stairs", "Intuit", "", "Easy"),
    ("DP", "Permutation Coefficient", "Amazon", "", "Medium"),
    ("DP", "Longest Repeating Subsequence", "Google Amazon", "", "Medium"),
    ("DP", "Pairs with Specific Difference", "Ola", "", "Medium"),
    ("DP", "Longest Subsequence-1", "Amazon", "", "Medium"),
    ("DP", "Coin Change", "Microsoft Samsung Barclays Apple Adobe", "", "Medium"),
    ("DP", "Longest Increasing Subsequence", "Amazon Google Facebook Fidelity", "", "Medium"),
    ("DP", "Longest Common Subsequence", "Siemens Amazon Google", "", "Medium"),
    ("DP", "Word Break (DP)", "Amazon Google Microsoft Walmart Apple IBM", "", "Medium"),
    ("DP", "Combination Sum IV", "Adobe Amazon Microsoft", "", "Medium"),
    ("DP", "House Robber", "Apple Uber", "", "Medium"),
    ("DP", "House Robber II", "Apple Uber", "", "Medium"),
    ("DP", "Decode Ways", "Adobe Uber", "", "Medium"),
    ("DP", "Unique Paths", "Google Microsoft", "", "Medium"),
    ("DP", "Jump Game", "Facebook Amazon Microsoft Google", "", "Medium"),
    ("DP", "0/1 Knapsack Problem", "Amazon Directi Flipkart Microsoft Morgan Stanley Oracle Payu Snapdeal Visa", "", "Medium"),
    ("DP", "nCr Computation", "Google", "", "Medium"),
    ("DP", "Catalan Number", "Amazon Google", "", "Medium"),
    ("DP", "Edit Distance", "Google Goldman Sachs Citrix", "", "Hard"),
    ("DP", "Subset Sum Problem", "Amazon Google", "", "Medium"),
    ("DP", "Gold Mine Problem", "Samsung", "", "Medium"),
    ("DP", "Assembly Line Scheduling", "Goldman Sachs", "", "Hard"),
    ("DP", "Maximize the Cut Segments", "Amazon OYO Rooms Microsoft", "", "Medium"),
    ("DP", "Maximum Sum Increasing Subsequence", "Amazon Morgan Stanley Microsoft", "", "Medium"),
    ("DP", "Count Subsequences with Product Less than K", "Goldman Sachs", "", "Hard"),
    ("DP", "Egg Dropping Puzzle", "Amazon D-E-Shaw Goldman Sachs Google Hike MakeMyTrip MAQ Software Microsoft Oracle Samsung", "", "Hard"),
    ("DP", "Max Length Chain", "Amazon Microsoft", "", "Medium"),
    ("DP", "Largest Square in Matrix", "Amazon Samsung", "", "Medium"),
    ("DP", "Maximum Path Sum in Matrix", "Amazon Microsoft OYO Directi", "", "Medium"),
    ("DP", "Minimum Number of Jumps", "Adobe Amazon Housing.com Walmart Microsoft Google Flipkart", "", "Hard"),
    ("DP", "Minimum Removals to Make Max-Min <= K", "Amazon", "", "Hard"),
    ("DP", "Longest Common Substring", "Webarch Club", "", "Medium"),
    ("DP", "Partition Equal Subset Sum (DP)", "Amazon Accolite Traveloka Adobe", "", "Medium"),
    ("DP", "Longest Palindromic Subsequence", "Amazon Google", "", "Medium"),
    ("DP", "Count Palindromic Subsequences (DP)", "Myntra", "", "Hard"),
    ("DP", "Longest Palindromic Substring (DP)", "Amazon Microsoft Samsung Visa", "", "Medium"),
    ("DP", "Longest Alternating Subsequence", "Ola", "", "Medium"),
    ("DP", "Weighted Job Scheduling", "Intuit", "", "Hard"),
    ("DP", "Coin Game", "Salesforce", "", "Hard"),
    ("DP", "Coin Game Winner", "Ola", "", "Hard"),
    ("DP", "Optimal Strategy for a Game", "Google IBM", "", "Hard"),
    ("DP", "Word Wrap (DP)", "Microsoft", "", "Hard"),
    ("DP", "Mobile Numeric Keypad", "Amazon Microsoft", "", "Hard"),
    ("DP", "Maximum Length of Pair Chain", "Amazon Microsoft", "", "Medium"),
    ("DP", "Matrix Chain Multiplication", "Walmart Flipkart", "", "Hard"),
    ("DP", "Maximum Profit by Buying and Selling at Most Twice", "Accolite Amazon Microsoft", "", "Hard"),
    ("DP", "Optimal BST", "Google", "", "Hard"),
    ("DP", "Largest Submatrix with Sum 0", "Amazon MakeMyTrip Microsoft", "", "Hard"),
    ("DP", "Largest Rectangular Sub-Matrix with Equal 1s and 0s", "Amazon Directi Intuit MakeMyTrip Microsoft Samsung Google Flipkart", "", "Hard"),

    # ── Bit Manipulation ──
    ("Bit Manipulation", "Count Set Bits in an Integer", "Adobe Apple", "", "Easy"),
    ("Bit Manipulation", "Find Two Non-Repeating Elements in Array", "Accolite Amazon FactSet Google MakeMyTrip Microsoft Qualcomm Samsung", "", "Medium"),
    ("Bit Manipulation", "Check if Number is Power of Two", "Adobe", "", "Easy"),
    ("Bit Manipulation", "Find Position of the Only Set Bit", "Microsoft", "", "Easy"),
    ("Bit Manipulation", "Count Bits to Flip to Convert A to B", "MAQ Software", "", "Easy"),
    ("Bit Manipulation", "Count Total Set Bits from 1 to N", "Microsoft", "", "Medium"),
    ("Bit Manipulation", "Copy Set Bits in a Range", "Facebook", "", "Medium"),
    ("Bit Manipulation", "Calculate Square without *, / and pow()", "Amazon", "", "Medium"),
    ("Bit Manipulation", "Divide Two Integers without *, / and mod", "Microsoft", "", "Medium"),
    ("Bit Manipulation", "Power Set", "Google Adobe Paytm", "", "Medium"),

    # ── Segment Trees ──
    ("Segment Trees", "Range Sum Query - Immutable", "", "", "Easy"),
    ("Segment Trees", "Range Minimum Query", "Google", "", "Medium"),
    ("Segment Trees", "Range Sum Query - Mutable", "Alibaba", "", "Medium"),
    ("Segment Trees", "Create Sorted Array through Instructions", "Samsung Accolite", "", "Hard"),
    ("Segment Trees", "Count of Range Sum", "Walmart", "", "Hard"),
    ("Segment Trees", "Count of Smaller Numbers After Self", "Codenation Google", "", "Hard"),
]


def seed_coding_questions(db_path):
    """Insert all DSA questions into the coding_questions table if empty."""
    import sqlite3
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row

    count = conn.execute("SELECT COUNT(*) FROM coding_questions").fetchone()[0]
    if count > 0:
        conn.close()
        return count  # Already seeded

    for topic, title, companies, remarks, difficulty in QUESTIONS:
        conn.execute(
            """
            INSERT INTO coding_questions (topic, title, companies, remarks, difficulty)
            VALUES (?, ?, ?, ?, ?)
            """,
            (topic, title, companies, remarks, difficulty),
        )
    conn.commit()
    total = conn.execute("SELECT COUNT(*) FROM coding_questions").fetchone()[0]
    conn.close()
    return total
